name = "dashboard"
main = "functions/worker.js"
compatibility_date = "2025-08-29"
type = "javascript"
account_id = "ccddcbf91b94e121d9d0d01d43d1675f"  # find in Cloudflare dashboard > Workers > Overview
